var Theme = {
    PRIMARY_FOREGROUND: '#DDDDDD',
    PRIMARY_BACKGROUND: '#3B3F44',
    SECONDARY_BACKGROUND: '#222222',
    PRIMARY_SELECTED: '#0080FF',
    PRIMARY_ACTIVE: '#00BB00',
    PRIMARY_CANCEL: '#FF8000',
    DISABLED_BACKGROUND: '#4D4D4D',
    DISABLED_FOREGROUND: '#999999'
}

export default Theme;